[package]
name = "miaxos/wasmio"
version = "0.0.2"
description = "S3 on the Edge"
wasmer-extra-flags = "--net --enable-threads --enable-bulk-memory --env CONFIG_FILE_LOCATION=/public/config.local.toml"

[fs]
"/public" = "./public"

[[module]]
name = "wasmio"
source = "target/wasm32-wasmer-wasi/debug/wasmio.wasi.wasm"

[[command]]
name = "wasmio"
module = "wasmio"
runner = "wasi@unstable_"
