[package]
name = "wasmio"
version = "0.0.1"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "WasmIO a S3 Implementation on steroid"
readme = "README.md"
keywords = [
    "wasm",
    "wasi",
    "s3",
]
categories = ["network-programming"]

[dependencies]
anyhow.workspace = true
axum.workspace = true
config.workspace = true
dotenv = "0.15"
futures.workspace = true
serde = { workspace = true, features = ["derive"] }

parking_lot = { version = "=0.12.1", features = ["nightly"] }
tokio = { version = "=1.24", default-features = false, features = [
    "rt-multi-thread",
    "macros",
    "fs",
    "io-util",
    "net",
    "signal",
] }

tower = { workspace = true, features = ["make", "log"] }
tower-http = { workspace = true, features = ["trace", "add-extension", "timeout", "limit"] }

tracing-subscriber = { workspace = true, features = ["fmt", "env-filter"] }
tracing.workspace = true

[build-dependencies]
chrono = "0.4.33"
